/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 12:46:58 GMT 2019
 */

package p_1;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import p_1.Amit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Amit_ESTest extends Amit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.RTerror();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.hoo();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.foo();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.boo();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.goo();
      assertEquals(0, int0);
  }
}
